### ISSUE TITLE
Variant: Tetris shapes are forbidden

### ISSUE THREAD

**Issue by JaniM** [JaniM/variant-go-server#41]
Specifically these shapes are forbidden:

```
 x   x  xx  x  xx
xx  xx   x  x  xx
x    x   x  x
            x
```

The shape has to be exact, so this is allowed, assuming the middle move is the last one played:

```
  x
xxx
  x
```

**Comment by sigs** [comment]
uhm... why though? All 4 stone groups are possible tetris blocks

**Comment by sigs** [comment]
Is this different from tetris go as implemented currently? :)

**Comment by JaniM** [comment]
Nope I am just bad at managing issues!
