### ISSUE TITLE
Client returning "Lost connection, reconnecting..." constantly

### ISSUE THREAD

**Issue by boykogoranov** [JaniM/variant-go-server#44]
Hey,
I wanted to contribute to the project and start learning Rust but I couldn't get the web UI working properly. 

Any suggestions as to why it would be stuck on "Lost connection, reconnecting..."? 

Centos 7
Rust installed from rustup
Wasm-pack as well
PGSQL9.6 running locally, not in a container, remote connection enabled and working

**Comment by JaniM** [comment]
Ah! I forgot to update the readme it seems. Use `wasm-pack build --dev -- --features local` to build the client locally.

**Comment by boykogoranov** [comment]
Same thing happens even if I build it like that. 
`[root@go-server www]# psql --host=192.168.88.55 --username=postgres --dbname=postgres
Password for user postgres:
psql (9.6.19)
Type "help" for help.

postgres=# \l
                                  List of databases
   Name    |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges
-----------+----------+----------+-------------+-------------+-----------------------
 postgres  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 template0 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
(3 rows)`

What else can I check? 

I have the apps running on ports 8088 and 8080. 
Firewall is disabled.
Selinux is disabled.

I am accessing localhost:8080 through an ssh-tunnel with:

ssh -L 8080:localhost:8080 root@192.168.88.55

Any other suggestions to get this running?

**Comment by boykogoranov** [comment]
Seems like it was something to do with the SSH tunnel. 

After installing a GUI on the server I can now connect to localhost BUT I get a different error. 

"No profile".  I'll close this one, work on the new error, seems like the tables aren't created properly for whatever reason.

**Comment by JaniM** [comment]
Ah... Seems I have forgotten to mention diesel in the readme too. 

```
cargo install diesel_cli --no-default-features --features postgres
cd server/
diesel migration run
```

**Comment by boykogoranov** [comment]
This is the worst part of my life as a devops engineer :( :D 

I saw the migration files but didn't know you need to run them through diesel, haven't had the time to run them manually either. 
I'll try this and let you know.
