### ISSUE TITLE
Variant: Rubics Go

### ISSUE THREAD

**Issue by isaiahstjohn** [JaniM/variant-go-server#56]
Instead of placing a stone, a player may choose to rotate vertically or horizontally. To explain the mechanics of this, it will be easier to use a concrete example. If they choose to rotate vertically, they would choose a column and a number of rows to rotate by. Suppose they choose column C and 5 rows. Then all stones in column C and all the columns to the right of column C would be shifted down 5 rows. So a stone at D5 would move to D10. They loop around, so a stone at F18 would move to F4.

Ideally, the player would be able to use the arrow keys to view the results of a rotation as they consider their move, so they don't have to try to visualize the rotation in their head.

**Comment by JaniM** [comment]
Seems like too much work for too few potential users to really consider.
